# Generated by Django 4.1.5 on 2023-01-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField()),
                ("Title", models.CharField(max_length=50)),
                ("body", models.TextField()),
            ],
        ),
    ]
