# Generated by Django 4.1.5 on 2023-01-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="Title",
            new_name="title",
        ),
    ]
